{{- /* apiVersion: v1
kind: Secret
metadata:
        #name: {{ include "mongotest-db.fullname" . }}-auth
  name: mongoauth #{{ .Release.Name }}-auth
  labels:
    {{- include "mongotest-db.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
 #MONGODB_ADMIN_PASSWORD:  {{ default "" .Values.database.adminpassword | b64enc | quote }}
  MONGODB_USER: {{ randAlphaNum 10 | b64enc | quote }}
  MONGODB_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  MONGODB_DATABASE: {{ default "" .Values.database.name_database | b64enc | quote }}
  MONGODB_URL: mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@mongodb/$(MONGODB_DATABASE)
  #"$(MONGODB_USER)"
-----------------my part --------------
   */}}

  {{- $admin_password := randAlphaNum 10 | b64enc | quote -}}
{{- $user := randAlphaNum 10 | b64enc | quote -}}
{{- $user_password := randAlphaNum 10 | b64enc | quote -}}
apiVersion: v1
kind: Secret
metadata:
        #name: {{ include "mongotest-db.fullname" . }}-auth
  name: mongoauth #{{ .Release.Name }}-auth
  labels:
    {{- include "mongotest-db.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_ADMIN_PASSWORD: {{ $admin_password }}
 #MONGODB_ADMIN_PASSWORD:  {{ default "" .Values.database.adminpassword | b64enc | quote }}
  MONGODB_USER: {{ $user }}
  MONGODB_PASSWORD: {{ $user_password }}
  MONGODB_DATABASE: {{ default "" .Values.database.name_database | b64enc | quote }}
#  MONGODB_URL: mongodb://{{ $user }}:{{ $user_password }}@mongodb/{{ default "" .Values.database.name_database | b64enc | quote }}



 