apiVersion: v1
kind: Secret
metadata:
        #name: {{ include "mongotest-db.fullname" . }}-auth
  name: mongoauth #{{ .Release.Name }}-auth
  labels:
    {{- include "mongotest-db.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
 #MONGODB_ADMIN_PASSWORD:  {{ default "" .Values.database.adminpassword | b64enc | quote }}
  MONGODB_USER: {{ randAlphaNum 10 | b64enc | quote }}
  MONGODB_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  MONGODB_DATABASE: {{ default "" .Values.database.name_database | b64enc | quote }}
#  MONGODB_URL: mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@mongodb/$(MONGODB_DATABASE)
  #"$(MONGODB_USER)"